apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{ .Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        ports:
        - containerPort: 8082
        env: 
          - name: CLOTHINGCONTAINER
            value: 0
          - name: WATERPIPE
            value: 0
          - name: SOLARPOWERGRID
            value: 0
          - name: BIKE
            value: 1
          - name: URL
            value: http://frost-server:8080/FROST-Server/v1.1
          - name: LOCATIONASOBSERVATION
            value: true

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  selector:
    app: {{.Values.name}}
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082