apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{ .Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        ports:
        - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  selector:
    app: {{.Values.name}}
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082