{{- range $.Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "50" | quote}}
spec:
  project: default
  source:
    path: {{ .path }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  destination:
    namespace: {{ .namespace }}
    server: {{ $.Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  {{- if .ignoreDifferences }}
  ignoreDifferences:
    {{- range .ignoreDifferences }}
    - group: {{ .group | quote }}
      kind: {{ .kind }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .jsonPointers }}
      jsonPointers:
      {{- range .jsonPointers }}
        - {{ . }}
      {{- end }}
      {{- end }}
      {{- if .jqPathExpressions }}
      jqPathExpressions:
      {{- range .jqPathExpressions }}
        - {{ . | squote }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
---
{{- end }}