apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frost-server.fullName" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
data:
  db.username: {{ .Values.frost.db.username }}
  db.password: {{ .Values.frost.db.password }}