spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tessaRuckstuhl/ArgoCD-Playground.git
    targetRevision: HEAD
applications:
  - name: root
    path: apps/
    namespace: default 
  - name: static-website
    path: static-website
    namespace: default
  - name: frost-server
    path: frost-server
    namespace: frostserver
  # - name: postgisdb
  #   path: postgisdb
  #   namespace: postgisdb
  # - name: grafana
  #   path: grafana
  #   namespace: grafana