spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tessaRuckstuhl/ArgoCD-Playground.git
    targetRevision: HEAD
applications:
  - name: root
    path: apps/
    namespace: default 
  - name: tessa-mynginx
    path: nginx
    namespace: default
  - name: secondnginx
    path: secondnginx
    namespace: default