spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tessaRuckstuhl/ArgoCD-Playground.git
    targetRevision: HEAD
applications:
  - name: root
    path: apps/
    namespace: default 
  # - name: static-website
  #   path: static-website
  #   namespace: static-website
  - name: frost-server
    path: frost-server
    namespace: frost-server
  # - name: simulator
  #   path: simulator
  #   namespace: simulator
  - name: angular-webapp
    path: angular-webapp
    namespace: angular-webapp
  # - name: postgisdb
  #   path: postgisdb
  #   namespace: postgisdb
  # - name: grafana
  #   path: grafana
  #   namespace: grafana